//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BanHangNoiThat_HeQTCSDL.DB_Main
{
    using System;
    using System.Collections.Generic;
    
    public partial class DonHangNhap
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DonHangNhap()
        {
            this.HangHoaNhaps = new HashSet<HangHoaNhap>();
        }
    
        public string MaDHNhap { get; set; }
        public Nullable<System.DateTime> Ngaynhap { get; set; }
        public Nullable<double> TongTien { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HangHoaNhap> HangHoaNhaps { get; set; }
    }
}
