//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BanHangNoiThat_HeQTCSDL.DB_Main
{
    using System;
    using System.Collections.Generic;
    
    public partial class DonHangBan
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DonHangBan()
        {
            this.HangHoaBans = new HashSet<HangHoaBan>();
        }
    
        public int MaDHBan { get; set; }
        public Nullable<System.DateTime> NgayBan { get; set; }
        public string MaKH { get; set; }
        public Nullable<double> TongTien { get; set; }
    
        public virtual KhachHang KhachHang { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HangHoaBan> HangHoaBans { get; set; }
    }
}
