//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BanHangNoiThat_HeQTCSDL.DB_Main
{
    using System;
    using System.Collections.Generic;
    
    public partial class GioHang
    {
        public string MaSP { get; set; }
        public string MaKH { get; set; }
        public string TenSP { get; set; }
        public Nullable<int> SoLuong { get; set; }
        public string HinhAnh { get; set; }
        public Nullable<double> GiaBan { get; set; }
        public string Maloai { get; set; }
    }
}
