//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BanHangNoiThat_HeQTCSDL.DB_Main
{
    using System;
    using System.Collections.Generic;
    
    public partial class SanPham
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SanPham()
        {
            this.HangHoaBans = new HashSet<HangHoaBan>();
            this.HangHoaNhaps = new HashSet<HangHoaNhap>();
        }
    
        public string MaSP { get; set; }
        public string MaLoai { get; set; }
        public string TenSP { get; set; }
        public string KichCo { get; set; }
        public string MauSac { get; set; }
        public string XuatXu { get; set; }
        public string MoTa { get; set; }
        public string Pic { get; set; }
        public Nullable<int> SoLuong { get; set; }
        public Nullable<double> GiaVon { get; set; }
        public Nullable<double> GiaBan { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HangHoaBan> HangHoaBans { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HangHoaNhap> HangHoaNhaps { get; set; }
        public virtual LoaiSanPham LoaiSanPham { get; set; }
    }
}
